---
label: project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: title
- name: body
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: body
